#!/bin/bash
# vim: ft=sh

use 'support/_image'

SUBCOMMAND_DESC='Image helper'
SUBCOMMAND_HELP=$(cat <<EOH
convert-pdf [folder_path] 		Converts to pdf all images in a folder and its children
EOH
)

PROJECT_NAME="shell_cli"
PROJECT_DIR="${PROJECTS_DIR}/${PROJECT_NAME}"

case ${1} in
  convert-pdf)
	local folder_path=${@:2}

	_convert_image_to_pdf ${folder_path}
  ;;
esac
