#!/bin/bash
# vim: ft=sh

use 'support/_setup'

SUBCOMMAND_DESC='Helper for setup your local environment'
SUBCOMMAND_HELP=$(cat <<EOH
check       Checks for prerequisites for development
EOH
)

case ${1} in
  check)
    in_cyan ">> dependencies for Persanal machine <<"
    _check_if_installed "convert" "Convert was not found. You can install gradle from homebrew 'brew install imagemagick'."
  ;;
esac
