#!/bin/bash
# vim: ft=sh

use 'support/_setup'
use 'support/_file'

SUBCOMMAND_DESC='Helper for setup your local environment'
SUBCOMMAND_HELP=$(cat <<EOH
run       Run wiremock point to the mappings folder
EOH
)

PROJECT_NAME="shell_cli"
PROJECT_DIR="${PROJECTS_DIR}/${PROJECT_NAME}"

WIREMOCK_PID_PATH=/tmp/wiremock_pid

case ${1} in
  run)
    wiremock_jar=$(get_properties wiremock_jar)
    java -jar $wiremock_jar -port 9999 &
    echo ${!} > ${WIREMOCK_PID_PATH}
  ;;
  stop)
    kill -TERM $(cat ${WIREMOCK_PID_PATH})
  ;;
esac
