#!/bin/bash
# vim: ft=sh

use 'support/_setup'

SUBCOMMAND_DESC='Helper for setup your local environment'
SUBCOMMAND_HELP=$(cat <<EOH
run       Run wiremock point to the mappings folder
EOH
)

WIREMOCK_PID_PATH=/tmp/wiremock_pid

case ${1} in
  run)
    java -jar wiremock-standalone-2.16.0.jar -port 9999 &
    echo ${!} > ${WIREMOCK_PID_PATH}
  ;;
  stop)
    kill -TERM $(cat ${WIREMOCK_PID_PATH})
  ;;
esac
