#!/bin/bash
# vim: ft=sh

use 'support/_setup'
use 'support/_file'

SUBCOMMAND_DESC='Helper for dealing with stubs'
SUBCOMMAND_HELP=$(cat <<EOH
start       Run wiremock point to the mappings folder
EOH
)

PROJECT_NAME="shell_cli"
PROJECT_DIR="${PROJECTS_DIR}/${PROJECT_NAME}"

WIREMOCK_PID_PATH=/tmp/wiremock_pid

case ${1} in
  start)
    wiremock_jar=$(get_properties wiremock_jar)
    wiremock_files=$(get_properties wiremock_files)
    
    java -jar $wiremock_jar -port 9999 --root-dir ${wiremock_files} &
    echo ${!} > ${WIREMOCK_PID_PATH}
  ;;
  stop)
    kill -TERM $(cat ${WIREMOCK_PID_PATH})
    rm ${WIREMOCK_PID_PATH}
  ;;
esac
