#!/bin/bash
# vim: ft=sh

function _validate_ids() {
  local ids_file=${1}
  local wiremock_host=$(get_properties wiremock_host)
  local produto_endpoint=$(get_properties produto_endpoint)

  ids_list=( $(_file_to_array ${ids_file}) )

  for id in ${ids_list[@]}; do
    in_cyan "Checking ID: ${id}"

    url="${wiremock_host}${produto_endpoint}${id}"
    
    http_response=$(curl -sL -w "%{http_code}\\n" "${url}" -o /dev/null)
    
    if [[ ${http_response} == 200 ]]; then
      in_green "Valid ID"
      echo "${id}" >> ${VALID_ID_FILE}
    else
      in_red "Invalid ID"
    fi

    (( count=$count+1 ))
    in_cyan "Processed ${count} out of ${#ids_list[@]}"
    in_cyan "========================||======================="
  done  
  
}